id: P008111
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG580
  title: བཀའ་གཙིགས་དང་རྡོ་རིང་གི་ཡི་གེ།
  author: ''
  volumes:
    22e0543757884835a8a4b7de7194629c:
      image_group_id: I1KG13749
      title: ''
      volume_number: 1
      total_pages: 78
ebook_metadata:
  title: བཀའ་གཙིགས་དང་རྡོ་རིང་གི་ཡི་གེ།
  author: ''
  sku: P008111
  cover: cover.jpg
  layers:
  - pagination
