id: P008111
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG580
  title: བཀའ་གཙིགས་དང་རྡོ་རིང་གི་ཡི་གེ།
  author: ''
  volumes:
    a36b2de5ba7148cdad822b48fe559095:
      image_group_id: I1KG13749
      title: Volume 1 of bka' gtsigs dang rdo ring gi yi ge/
      volume_number: 1
      total_pages: 78
      base_file: v001.txt
