id: ID95B7607
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T22:27:24+00:00'
last_modified: '2022-06-09T04:34:51.168527+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG580
  title: བཀའ་གཙིགས་དང་རྡོ་རིང་གི་ཡི་གེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    6CAC:
      image_group_id: I1KG13749
      title: Volume 1 of bka' gtsigs dang rdo ring gi yi ge/
      total_pages: 78
      order: 1
      base_file: 6CAC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
